# Generated by Django 4.0.2 on 2022-02-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupocliente',
            name='apipass',
        ),
        migrations.RemoveField(
            model_name='grupocliente',
            name='apitoken',
        ),
        migrations.RemoveField(
            model_name='grupocliente',
            name='apiuser',
        ),
    ]
