# Generated by Django 4.0.2 on 2022-02-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_grupocliente_apipass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocliente',
            name='telefone',
            field=models.CharField(max_length=25, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Pendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_maquina', models.CharField(max_length=246, verbose_name='Serial da Maquina')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('grupo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grupocliente')),
            ],
        ),
    ]
