# Generated by Django 4.0.2 on 2022-02-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pendencias_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=64, verbose_name='Razão Social')),
                ('nome_reduzido', models.CharField(max_length=15, verbose_name='Nome Reduzido')),
                ('telefone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('grupo_emrpesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grupocliente', verbose_name='grupo_cliente_cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Pendencias',
        ),
    ]
