# Generated by Django 4.0.2 on 2022-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pendencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Ativo'),
            preserve_default=False,
        ),
    ]
