# Generated by Django 4.0.2 on 2022-02-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cliente_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='grupo_emrpesa',
            new_name='grupo_empresa',
        ),
    ]
