# Generated by Django 4.0.2 on 2022-02-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_grupo_emrpesa_cliente_grupo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendencias',
            name='aprovado_recusado',
            field=models.BooleanField(default=False, verbose_name='Aprovado ou Recusado'),
            preserve_default=False,
        ),
    ]
