# Generated by Django 4.0.2 on 2022-02-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pendencias_aprovado_recusado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pendencias',
        ),
    ]
