# Generated by Django 4.0.2 on 2022-02-14 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_pendencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_maquina', models.CharField(max_length=246, verbose_name='Serial da Maquina')),
                ('aprovado_recusado', models.BooleanField(verbose_name='Aprovado ou Recusado')),
                ('data_expira', models.DateField(verbose_name='Expira em')),
                ('status', models.IntegerField(verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente', verbose_name='cliente_pendencias')),
            ],
        ),
    ]
