# Generated by Django 4.0.2 on 2022-02-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pendencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendencias',
            name='aprovado_recusado',
        ),
    ]
