# Generated by Django 4.0.2 on 2022-02-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pendencias',
            new_name='Estacoes',
        ),
    ]
