# Generated by Django 4.0.2 on 2022-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_pendencias_estacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacoes',
            name='data_expira',
            field=models.DateField(null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='estacoes',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Ativo'),
        ),
    ]
