# Generated by Django 4.0.2 on 2022-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_estacoes_data_expira_alter_estacoes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacoes',
            name='senha_api',
            field=models.CharField(max_length=128, null=True, verbose_name='Senha API'),
        ),
    ]
