# Generated by Django 4.0.2 on 2022-02-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_estacoes_senha_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacoes',
            name='senha_api',
        ),
        migrations.AlterField(
            model_name='estacoes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente', verbose_name='estacao_cliente'),
        ),
    ]
