# Generated by Django 4.0.2 on 2022-02-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_estacoes_senha_api_alter_estacoes_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacoes',
            name='data_expira',
            field=models.CharField(max_length=25, null=True, verbose_name='Expira em'),
        ),
    ]
