# Generated by Django 4.0.2 on 2022-02-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_estacoes_data_expira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacoes',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Estacoes',
        ),
        migrations.DeleteModel(
            name='GrupoCliente',
        ),
    ]
