# Generated by Django 4.0.2 on 2022-02-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0019_remove_estacoes_cliente_delete_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=64, verbose_name='Razão Social')),
                ('nome_reduzido', models.CharField(max_length=15, verbose_name='Nome Reduzido')),
                ('telefone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('status', models.IntegerField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=64, verbose_name='Descrição')),
                ('nomecontato', models.CharField(max_length=64, verbose_name='Nome do Contato')),
                ('telefone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('dtcadastro', models.DateTimeField(auto_now=True, verbose_name='Data do Cadastro')),
                ('status', models.IntegerField(verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Estacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_maquina', models.CharField(max_length=246, verbose_name='Serial da Maquina')),
                ('data_expira', models.CharField(max_length=25, null=True, verbose_name='Expira em')),
                ('status', models.IntegerField(null=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cliente', verbose_name='estacao_cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grupocliente', verbose_name='grupo_cliente_cliente'),
        ),
    ]
